"""create flask_sessions table

Revision ID: 06006069890c
Revises: 
Create Date: 2017-12-11 21:29:45.991072

"""
from alembic import op
import flask_sqlalchemy_bundle
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06006069890c'
down_revision = None
branch_labels = ('flask_session_bundle',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flask_sessions',
    sa.Column('created_at', flask_sqlalchemy_bundle.sqla.types.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', flask_sqlalchemy_bundle.sqla.types.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('expiry', flask_sqlalchemy_bundle.sqla.types.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flask_sessions')),
    sa.UniqueConstraint('session_id', name=op.f('uq_flask_sessions_session_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flask_sessions')
    # ### end Alembic commands ###
